### ISSUE TITLE
How to prevent HTML escaping

### ISSUE THREAD

**Issue by Lloople** [calebporzio/gitdown#3]
First of all, thank you for this amazing package 🙌

I'm already using it in my personal website. The process was smooth and the result is really great.

The only issue I'm having is when I try to embed tweets. You can [check it here](https://davidllop.com/posts/building-my-own-blog#user-content-freeks-work)

I searched for a while but can't find anything useful. Maybe it's not even possible.

I already have the `allowIframe` option set to `true`.

Thank you,

David

**Comment by calebporzio** [comment]
Ah yes, I only escape "iframes" not "script" tags. I'd be open to a pull request where we change the option (or add one) to: "allowDangerousTags" that allows "scripts" "iframes" and I forget the other ones GitHub escapes.

Is this something you'd be interested in contributing?

**Comment by Lloople** [comment]
Sure!

I’ll check it out tomorrow 👍
